version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    container_name: gorm
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME} 
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: gorm@gorm.gorm
      PGADMIN_DEFAULT_PASSWORD: gorm
    ports:
      - "5050:80"

volumes:
  postgres:     