http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

# cache:
#   ttl: 60s

# fileStorage:
#   url: ams3.digitaloceanspaces.com
#   bucket: courses

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days
  verificationCodeLength: 8
limiter:
  rps: 10
  burst: 20
  ttl: 10m
# smtp:
#   host: "mail.privateemail.com"
#   port: 587
#   from: "no-reply@creatly.me"
